### ISSUE TITLE
tparse can hide the existence of packages without tests in them

### ISSUE THREAD

**Issue by marco-m** [mfridman/tparse#66]
Hello @mfridman :-)

When a Go module has two packages, one of which has zero tests, and go test is run with the all paths option `./...`, then tparse completely hides the existence of the package without tests.

I made a as-small-as-possible repro at https://github.com/marco-m/tparse-bugs/tree/master/02.

**Comment by mfridman** [comment]
Thanks for a repro (as always). You'll want the `-notests` flag here. I found in very large monorepos `./...` produces a lot of noise, so "no test files" are hidden by default unless you opt-in to see them.

The exception is if there is one and only one "no tests" package with no other passed packages. This almost always happens when a user targeted or incorrectly matched a package.

**Comment by marco-m** [comment]
Ah, I should have read the docs better! And you explanation for the default makes sense.
Thanks, I really like the new tparse.
