### ISSUE TITLE
`-format markdown` isn't 100% markdown and `-nocolor` still outputs colour

### ISSUE THREAD

**Issue by alecthomas** [mfridman/tparse#71]
I'm attempting to use `tparse` in Buildkite to output a nice test summary, but the output is not 100% markdown. There appears to be normal(ish) test output prepended to markdown:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/41767/172611449-6fcb1ca3-adb6-44f2-a3f2-5150e331c4a4.png">

Which renders like this in Buildkite:

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/41767/172612023-f77f36a9-b705-4fb7-bd54-1d2c5464d3d4.png">

I'm using terminal-to-html to work around the colour issue.

**Comment by alecthomas** [comment]
My ideal would be that `--markdown` would convert all output to Markdown, including the colour.

**Comment by alecthomas** [comment]
I wanted to use `-all` in our monorepo, but the output is just overwhelming, but your idea of collapsible sections would be a great solution to that.

**Comment by mfridman** [comment]
> I wanted to use -all in our monorepo, but the output is just overwhelming, but your idea of collapsible sections would be a great solution to that.

Ye, for very large monorepos `-all` (`-skip` and `-pass` combined) is overwhelming. The idea behind this flag was to pair it with `-slow N` .. which reports slowest N (passed) tests per package.

Example:

```
go test time -cover -json -count=1 | tparse -slow 2 -all 
```

Will limit -all output to the 2 slowest passed tests from the time package, out of 157. This way can quickly see that `TestTimerStopStress` and `TestTicker` are the worst offenders.

| STATUS | ELAPSED |        TEST         | PACKAGE |
|--------|---------|---------------------|---------|
| SKIP   |    0.00 | TestCountMallocs    | time    |
| PASS   |    3.00 | TestTimerStopStress | time    |
| PASS   |    1.10 | TestTicker          | time    |

| STATUS | ELAPSED | PACKAGE | COVER | PASS | FAIL | SKIP |
|--------|---------|---------|-------|------|------|------|
| PASS   | 7.66s   | time    | 91.8% |  157 |    0 |    1 |

**Comment by alecthomas** [comment]
Ah nice, I wasn't quite sure what `-slow` did TBH.

**Comment by mfridman** [comment]
**Before**             |  **After**
:-------------------------:|:-------------------------:
<img width="744" alt="CleanShot 2022-07-04 at 18 59 48@2x" src="https://user-images.githubusercontent.com/6278244/177223803-baaee5de-ab46-4490-b400-9d339ac35893.png">  |  <img width="610" alt="CleanShot 2022-07-04 at 19 01 30@2x" src="https://user-images.githubusercontent.com/6278244/177223777-bff6e8ea-7c45-4c0b-b042-1fd2abb0af81.png">

Alright, I think I got this into a workable state. For markdown output, needed to wrap the failed test output, otherwise, there is weird formatting with the way output contains indents that trigger markdown code fences.

And on local CI it continues to work like normal:

<img width="701" alt="CleanShot 2022-07-04 at 19 07 09@2x" src="https://user-images.githubusercontent.com/6278244/177224091-a4dc4b58-d045-4a70-b8a7-ec28c73bc2d5.png">

And then GitHub CI it also looks descent.

<img width="497" alt="CleanShot 2022-07-04 at 19 07 52@2x" src="https://user-images.githubusercontent.com/6278244/177224143-a87c6648-7f19-4fe3-9730-08e61eb72c7f.png">

Going to clean this up and try and merge a branch tonight.

**Comment by mfridman** [comment]
Ended up using `##` for the package headers between failed tests. Here is what it looks like now...

Still some work to do to polish it, but I think this is in a better state as before.

![image](https://user-images.githubusercontent.com/6278244/177244382-e69b1455-d567-4056-977f-0b0ddaaaeaca.png)

**Comment by mfridman** [comment]
I think the markdown looks a bit nicer now. It uses markdown sections to automatically collapse the overwhelming tests. Here I use `-slow 20` to display the slowest 20 tests only.

<img width="838" alt="CleanShot 2022-07-31 at 21 10 07@2x" src="https://user-images.githubusercontent.com/6278244/182054325-498cb201-c9d5-4eea-a591-919503c99a06.png">
