### ISSUE TITLE
Make smallscreen work for test table as well

### ISSUE THREAD

**Issue by jak103** [mfridman/tparse#91]
Awesome tool! Thank you so much!

There is an option -smallscreen that will stack the path for the package in the summary table. I like this because I prefer the more dense table you get without this option. 

However, the test table always stacks the package path. 

What do you think about making the  default behavior on the test table be the more dense version and then the -smallscreen can make both tables stack the path? It would make the two tables more consistent.

**Comment by mfridman** [comment]
What version are you using? Iirc in https://github.com/mfridman/tparse/pull/81 we improved package shortening

If this isn't what you were thinking, can you give me an example of what you're seeing and what the desired output would be?

**Comment by jak103** [comment]
The test summary looks like this:
![Screenshot 2023-03-18 at 12 48 06 PM](https://user-images.githubusercontent.com/964779/226129986-a4890905-ceb5-466e-9dd9-51c858b7cf6a.png)
The package summary looks like this:
![Screenshot 2023-03-18 at 12 51 04 PM](https://user-images.githubusercontent.com/964779/226130095-23690759-28cf-499a-8f22-925218cc1df6.png)

I'd like the test summary to not use the smallscreen format, and instead give the package on one line.

**Comment by mfridman** [comment]
I just re-read this and it finally made sense, sorry for the delay.

To use the example you shared, the `pkg/devsite/config` should be **one line** instead of split across multiple lines like the Test names in the Test Summary Table.

@c2h5oh I'm curious when you implemented #81 .. what was the rationale for shortening the package name.

Do you see an issue if we kept the shortening but concatenated the package name? It'll make the table ~slightly wider, but maybe would be okay? Granted some folks have really long package names .. so this may be the main reason.

**Comment by mfridman** [comment]
Put up https://github.com/mfridman/tparse/pull/96 to address this, @jak103 was this what you had in mind? Added some screenshots as an example.
